# #######################
# IMAGE-SIZE: 637.23 MB #
# #######################
#
# docker build -f Dockerfiles/Dockerfile_jar_simple -t hello-docker:latest .
# docker compose up -d
# curl http://localhost:8080
# docker compose down -v
#
FROM maven:3.9.9-amazoncorretto-21-debian-bookworm

WORKDIR /app

# Maven Wrapper + Dependencies
COPY mvnw .
COPY .mvn/ .mvn/
COPY pom.xml .
RUN ./mvnw dependency:go-offline

# Source Code
COPY src/ src/

# Build jar
RUN ./mvnw clean package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/hello-docker.jar"]