# ######################
# IMAGE-SIZE: 332.3 MB #
# ######################

# #######################################################################################
# docker build -f Dockerfiles/Dockerfile_jar_stages -t hello-docker:latest .
# docker compose up -d
# curl http://localhost:8080
# docker compose down -v
# #######################################################################################

# --- STAGE 1: Build image ---
FROM maven:3.9.9-amazoncorretto-21-debian-bookworm AS build

WORKDIR /app

# Maven Wrapper + Dependencies
COPY mvnw .
COPY .mvn/ .mvn/
COPY pom.xml .
RUN ./mvnw dependency:go-offline

# Source Code
COPY src/ src/

# Build jar
RUN ./mvnw clean package -DskipTests

# --- STAGE 2: Final minimal image ---
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/hello-docker.jar /app/hello-docker.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/hello-docker.jar"]